logging:
  appenders:
    - type: console
      logFormat: "%-5p [%d{ISO8601,UTC}] %c{30}: %m%n%rEx"

database:
  driverClass: com.mysql.cj.jdbc.Driver
  user: ${env:DB_USER:-root}
  password: ${env:DB_PASS:-root}
  url: ${env:DB_URL:-jdbc:mysql://localhost:3306/spark}

keycloak:
  realm: spark
  auth-server-url: http://localhost:8433/
  ssl-required: external
  resource: backend
  #  verify-token-audience: true
  credentials:
    secret: wIQXbUzliptZx3Hsa8M6SLnvKGIG0VbS
  confidential-port: 0
  bearer-only: true
#  policy-enforcer: { }
